#version: '3.8'

services:
  bankingappapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Database=bankingAppDB;Username=BankingAppAPI;Password=Banking123
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bankingAppDB
      - POSTGRES_USER=BankingAppAPI
      - POSTGRES_PASSWORD=Banking123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: